name: Delete Artifacts

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List all artifacts
        id: list-artifacts
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/artifacts \
          | jq -r '.artifacts[] | select(.expired == false) | .id' > artifacts.txt

      - name: Delete artifacts
        if: ${{ steps.list-artifacts.outputs.artifacts }}
        run: |
          for artifact_id in $(cat artifacts.txt); do
            gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/${artifact_id}
          done
