name: Delete Artifacts

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: List all artifacts
        id: list-artifacts
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/artifacts \
          | jq -r '.artifacts[] | select(.expired == false) | .id' > artifacts.txt

      - name: Delete artifacts
        run: |
          for artifact_id in $(cat artifacts.txt); do
            gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/${artifact_id}
          done
